import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AOSInitializer from "./AOSInitializer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Everest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AOSInitializer /> {/* Initialize AOS */}
        {children}
      </body>
    </html>
  );
}
